version: '3'
networks:
  shop_net:
    ipam:
      config:
        - subnet: 192.168.65.0/24
          gateway: 192.168.65.1
services:
  db:
    image: postgres:latest
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=semaj
      - POSTGRES_PASSWORD=semaj
      - POSTGRES_DB=ecommerce_db
    networks:
      shop_net:
        ipv4_address: 192.168.65.2
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=semaj@rootmail.com
      - PGADMIN_DEFAULT_PASSWORD=semaj
    depends_on:
      - db
    networks:
      shop_net:
        ipv4_address: 192.168.65.3